
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Wow from "../components/wow";
import Header from "../components/Header";
import Footer from "../components/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "ThermWin System Windows",
  description: "Generated by ThermWin System Windows",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="img/png" sizes="32x32" href="/favicon-32x32.png" />
          <link rel="icon" type="img/png" sizes="16x16" href="/favicon-16x16.png" />
            <link rel="manifest" href="/site.webmanifest"></link>
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
              <div className={'main-content'}>
                <Wow />
                <Header />
                {children}
                <Footer />
              </div>
            </body>
          </html>
          );
}
